### ISSUE TITLE
Using local DHT mirror causes resolver to crash

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-resolver#98]
When I point the resolver to my local DHT mirror, the resolver crashes with the following error.

``` python
DEBUG:resolver:Memcache get: bob
Traceback (most recent call last):
  File "/srv/resolver/venv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/srv/resolver/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/srv/resolver/venv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/resolver/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/srv/resolver/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/srv/resolver/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/srv/resolver/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/srv/resolver/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/resolver/resolver/crossdomain.py", line 60, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/srv/resolver/resolver/server.py", line 252, in get_users
    info = get_profile(username, refresh=refresh)
  File "/srv/resolver/resolver/server.py", line 161, in get_profile
    profile = fetch_from_dht(profile_hash)
  File "/srv/resolver/resolver/server.py", line 101, in fetch_from_dht
    dht_resp = dht_resp[0]
KeyError: 0
```

The same DHT mirror works fine when used in blockstack's `client.ini`.

Using mirror.blockstack.org works as well.

My `config_local.py`:

``` python
import logging
log = logging.getLogger()

log.debug('using: config_local.py')

DEBUG = True

MEMCACHED_USERNAME = None
MEMCACHED_PASSWORD = None

BLOCKSTORED_IP = '127.0.0.1'
BLOCKSTORED_PORT = 6264
#DHT_MIRROR_IP = 'mirror.blockstack.org'
DHT_MIRROR_IP = '127.0.0.1'
DHT_MIRROR_PORT = 6266

MEMCACHED_TIMEOUT = 12 * 60 * 60
USERSTATS_TIMEOUT = 60 * 60
MEMCACHED_ENABLED = True

MEMCACHED_SERVERS = ['127.0.0.1:11211']

try:
    API_USERNAME = os.environ['API_USERNAME']
    API_PASSWORD = os.environ['API_PASSWORD']
except:
    API_USERNAME = 'default'
    API_PASSWORD = 'default'

```

**Comment by muneeb-ali** [comment]
This was fixed earlier. Thanks @larrysalibra!
